document.querySelector('main').insertAdjacentHTML('beforeend',`<section id="family" class="view hide"><div class="family-shell">
  <div class="family-intro"><div><span class="ey">ESCUELA DE FAMILIAS</span><h1>Crecer en calma</h1><p>Entender antes de corregir.</p></div><div class="family-progress-wrap"><strong id="familyProgressText">0 de 5 módulos</strong><div class="family-progress"><span id="familyProgressFill"></span></div></div></div>
  <nav class="family-tabs" aria-label="Secciones de Crecer en calma"><button class="family-tab active" data-family-tab="familyLearn">Aprender</button><button class="family-tab" data-family-tab="familyABC">Practicar ABC</button><button class="family-tab" data-family-tab="familyPlan">Mi plan semanal</button></nav>
  <section id="familyLearn" class="family-panel active"><aside id="familyModuleList" class="family-modules" aria-label="Módulos de formación"></aside><article id="familyLesson" class="family-lesson" aria-live="polite"></article></section>
  <section id="familyABC" class="family-panel"><div class="family-tool-grid"><form id="familyABCForm" class="family-card"><span class="family-label">HERRAMIENTA PRÁCTICA</span><h2>Registro ABC sin etiquetas</h2><p>Describe un episodio concreto. Registra solamente lo que una cámara habría captado.</p><label><b>A · ¿Qué ocurrió justo antes?</b><textarea id="familyAntecedent" required placeholder="Ej.: Le indiqué que era momento de guardar los carros."></textarea></label><label><b>B · ¿Qué hizo exactamente?</b><textarea id="familyBehavior" required placeholder="Ej.: Gritó, lanzó dos carros y se alejó."></textarea></label><label><b>C · ¿Qué ocurrió después?</b><textarea id="familyConsequence" required placeholder="Ej.: El adulto guardó los juguetes por él."></textarea></label><label><b>Hipótesis provisional</b><select id="familyHypothesis"><option>Necesita más observaciones</option><option>Obtener atención</option><option>Escapar o aplazar una demanda</option><option>Acceder a un objeto o actividad</option><option>Buscar o evitar estimulación sensorial</option></select></label><small>Una observación no demuestra la función. Busca patrones durante varios días.</small><button class="primary" type="submit">Guardar en este dispositivo</button><div id="familyABCNotice" class="family-notice hidden">Registro guardado sin información personal.</div></form><aside class="family-card"><h2>Registros recientes</h2><p>Se conservan máximo cinco episodios anónimos.</p><div id="familySavedLogs"></div><button id="familyClearLogs" class="secondary" type="button">Borrar registros</button></aside></div></section>
  <section id="familyPlan" class="family-panel"><div class="family-tool-grid"><form id="familyPlanForm" class="family-card"><div class="family-callout"><strong>Una sola meta por semana</strong><span>Pequeña, observable y útil para el niño.</span></div><label><b>Conducta que queremos facilitar</b><input id="familyTarget" placeholder="Ej.: Pedir descanso antes de lanzar objetos"></label><label><b>Alternativa que enseñaremos</b><input id="familyAlternative" placeholder="Ej.: Entregar la tarjeta DESCANSO"></label><label><b>Qué hará el adulto antes</b><textarea id="familyPrevention" placeholder="Ej.: Avisar el cambio y reducir la tarea."></textarea></label><label><b>Qué ocurrirá cuando lo intente</b><textarea id="familyReinforcement" placeholder="Ej.: Conceder la pausa y reconocer la petición."></textarea></label><button class="primary" type="submit">Guardar mi plan</button><div id="familyPlanNotice" class="family-notice hidden">Plan guardado en este dispositivo.</div></form><aside class="family-card"><h2>Lista de comprobación</h2><div id="familyChecklist" class="family-checklist"></div></aside></div></section>
  <div class="family-scope"><strong>Importante:</strong> este recurso acompaña la formación de cuidadores; no diagnostica ni sustituye la valoración profesional. No escribas nombres ni datos identificables del niño.</div>
</div></section>`);

const FAMILY_MODULES=[
  {title:'Observar sin etiquetar',time:'4 min',lead:'Comprendemos mejor la conducta cuando describimos lo ocurrido, no cuando definimos al niño.',principle:'Cambia “es desobediente” por una acción que cualquier persona pueda observar y contar.',steps:['Elige una sola situación frecuente.','Describe qué ocurrió antes, qué hizo y qué sucedió después.','Registra también cuándo la conducta no aparece.'],example:'En vez de “hizo una pataleta”, escribe: lloró, se acostó y pateó durante tres minutos.'},
  {title:'Buscar la función',time:'5 min',lead:'Una conducta puede ayudar a obtener algo, escapar, recibir atención o regular una experiencia sensorial.',principle:'La función es una hipótesis basada en patrones; nunca se concluye con un solo episodio.',steps:['Compara varios registros ABC.','Pregunta qué consiguió o evitó el niño.','Considera cansancio, dolor, dificultad y sobrecarga.'],example:'Si lanzar materiales consigue que la tarea termine repetidamente, podría estar ayudándole a escapar de la demanda.'},
  {title:'Prevenir antes de corregir',time:'4 min',lead:'Modificar lo que sucede antes suele ser más efectivo que reaccionar cuando el niño ya está desbordado.',principle:'Anticipar, simplificar y ofrecer elección reduce la necesidad de conductas problemáticas.',steps:['Avisa los cambios con una imagen o temporizador.','Da una instrucción concreta de un paso.','Alterna actividad breve, movimiento y descanso.'],example:'“Primero guardamos tres carros; después burbujas” es más claro que “compórtate y ordena todo”.'},
  {title:'Enseñar una alternativa',time:'5 min',lead:'No basta con pedirle que deje de hacer algo: necesita una manera sencilla de conseguir la misma finalidad.',principle:'La alternativa debe ser más fácil, rápida y efectiva que la conducta que queremos disminuir.',steps:['Enséñala cuando esté tranquilo.','Modela y ayuda sin exigir perfección.','Practica primero en situaciones fáciles.'],example:'Si grita para terminar, enséñale a decir, señalar o entregar una tarjeta de “terminé” o “descanso”.'},
  {title:'Reforzar y revisar',time:'4 min',lead:'El aprendizaje aumenta cuando la respuesta apropiada recibe una consecuencia inmediata y significativa.',principle:'Reconoce la acción concreta: “Pediste ayuda”, en lugar de decir solamente “muy bien”.',steps:['Refuerza inmediatamente el intento adecuado.','Mantén una meta pequeña durante una semana.','Revisa los datos y ajusta el apoyo, no culpes al niño.'],example:'Si entrega “descanso”, permite una pausa breve y ayúdale a regresar con una tarea más pequeña.'}
];
const FAMILY_CHECKS=['La meta es observable','La alternativa cumple la misma función','Puede comunicar “no” o “descanso”','El adulto anticipará la situación','El refuerzo será inmediato','Se observará durante una semana'];
let familyCurrent=Number(localStorage.getItem('mb-family-current')||0);
let familyDone=JSON.parse(localStorage.getItem('mb-family-done')||'[]');
const familyEsc=value=>{const div=document.createElement('div');div.textContent=value;return div.innerHTML};

function renderFamily(){
  $('#familyModuleList').innerHTML=FAMILY_MODULES.map((m,i)=>`<button class="family-module ${i===familyCurrent?'active':''} ${familyDone.includes(i)?'done':''}" data-family-module="${i}"><span class="family-module-num">${familyDone.includes(i)?'✓':i+1}</span><span><b>${m.title}</b><small>${m.time}</small></span></button>`).join('');
  const m=FAMILY_MODULES[familyCurrent];
  $('#familyLesson').innerHTML=`<span class="family-label">MÓDULO ${familyCurrent+1} DE 5</span><h2>${m.title}</h2><p class="family-lead">${m.lead}</p><div class="family-principle">${m.principle}</div><div class="family-steps">${m.steps.map((s,i)=>`<div class="family-step"><b>${i+1}.</b><span>${s}</span></div>`).join('')}</div><div class="family-example"><b>Ejemplo cotidiano</b><br>${m.example}</div><div class="family-actions"><button id="familyPrev" class="secondary" ${familyCurrent===0?'disabled':''}>Anterior</button><button id="familyComplete" class="primary">${familyDone.includes(familyCurrent)?'Módulo completado':'Marcar y continuar'}</button></div>`;
  $$('[data-family-module]').forEach(button=>button.onclick=()=>{familyCurrent=Number(button.dataset.familyModule);localStorage.setItem('mb-family-current',familyCurrent);renderFamily()});
  $('#familyPrev').onclick=()=>{if(familyCurrent>0){familyCurrent--;renderFamily()}};
  $('#familyComplete').onclick=()=>{if(!familyDone.includes(familyCurrent))familyDone.push(familyCurrent);localStorage.setItem('mb-family-done',JSON.stringify(familyDone));if(familyCurrent<4)familyCurrent++;renderFamily()};
  $('#familyProgressText').textContent=`${familyDone.length} de 5 módulos`;
  $('#familyProgressFill').style.width=`${familyDone.length*20}%`;
}

$$('.family-tab').forEach(button=>button.onclick=()=>{
  $$('.family-tab,.family-panel').forEach(x=>x.classList.remove('active'));
  button.classList.add('active');$('#'+button.dataset.familyTab).classList.add('active');
});

const getFamilyLogs=()=>JSON.parse(localStorage.getItem('mb-family-abc')||'[]');
function renderFamilyLogs(){
  const logs=getFamilyLogs();
  $('#familySavedLogs').innerHTML=logs.length?logs.map(log=>`<div class="family-log"><small>${log.date} · ${familyEsc(log.hypothesis)}</small><br><b>Antes:</b> ${familyEsc(log.antecedent)}<br><b>Conducta:</b> ${familyEsc(log.behavior)}<br><b>Después:</b> ${familyEsc(log.consequence)}</div>`).join(''):'<p>No hay registros todavía.</p>';
}
$('#familyABCForm').onsubmit=event=>{
  event.preventDefault();const logs=getFamilyLogs();logs.unshift({date:new Date().toLocaleDateString('es-CO'),antecedent:$('#familyAntecedent').value,behavior:$('#familyBehavior').value,consequence:$('#familyConsequence').value,hypothesis:$('#familyHypothesis').value});localStorage.setItem('mb-family-abc',JSON.stringify(logs.slice(0,5)));event.target.reset();renderFamilyLogs();$('#familyABCNotice').classList.remove('hidden');setTimeout(()=>$('#familyABCNotice').classList.add('hidden'),2500);
};
$('#familyClearLogs').onclick=()=>{localStorage.removeItem('mb-family-abc');renderFamilyLogs()};

$('#familyChecklist').innerHTML=FAMILY_CHECKS.map((text,i)=>`<label class="family-check"><input type="checkbox" data-family-check="${i}"><span>${text}</span></label>`).join('');
const familyPlanIds=['familyTarget','familyAlternative','familyPrevention','familyReinforcement'];
const savedFamilyPlan=JSON.parse(localStorage.getItem('mb-family-plan')||'{}');familyPlanIds.forEach(id=>{$('#'+id).value=savedFamilyPlan[id]||''});
$('#familyPlanForm').onsubmit=event=>{event.preventDefault();const plan={};familyPlanIds.forEach(id=>plan[id]=$('#'+id).value);localStorage.setItem('mb-family-plan',JSON.stringify(plan));$('#familyPlanNotice').classList.remove('hidden');setTimeout(()=>$('#familyPlanNotice').classList.add('hidden'),2500)};

renderFamily();renderFamilyLogs();
